/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat/index.vue')['default']
    ChooseApi: typeof import('./src/components/chat/chooseApi.vue')['default']
    ChooseModel: typeof import('./src/components/chat/chooseModel.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./src/components/chat/empty.vue')['default']
    EpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default']
    EpClock: typeof import('~icons/ep/clock')['default']
    EpCloseBold: typeof import('~icons/ep/close-bold')['default']
    EpDelete: typeof import('~icons/ep/delete')['default']
    EpLoading: typeof import('~icons/ep/loading')['default']
    EpPicture: typeof import('~icons/ep/picture')['default']
    EpPromotion: typeof import('~icons/ep/promotion')['default']
    EpSetting: typeof import('~icons/ep/setting')['default']
    History: typeof import('./src/components/history/index.vue')['default']
    Message: typeof import('./src/components/chat/message.vue')['default']
    Setting: typeof import('./src/components/chat/setting.vue')['default']
  }
}
